v: 2.6.0
overrideConfig: false
ie:
  - DS_Store
  - less
  - scss
  - js
id:
  - scss
  - .svn
  - .sass-cache
  - fonts
  - icons
cleanPublic: 'false'
patternStates:
  - inprogress
  - inreview
  - complete
styleGuideExcludes: ''
cacheBusterOn: 'true'
exportDir: export
publicDir: ../../../dist/pl-default/
sourceDir: ../../../source/default/
defaultPattern: protons-welcome
defaultShowPatternInfo: false
ishMinimum: '240'
ishMaximum: '2600'
ishControlsHide:
  - hay
lineageMatch: '{%([ ]+)?include( |\()[&quot;\&#039;]([A-Za-z0-9-_]+)[&quot;\&#039;](\))?(.*)%}'
lineageMatchKey: 3
patternExtension: twig
twigDebug: true
twigAutoescape: false
twigDefaultDateFormat: ''
twigDefaultIntervalFormat: ''
twigMacroExt: macro.twig
twigFilterExt: filter.php
twigFunctionExt: function.php
twigTagExt: tag.php
twigTestExt: test.php
styleguideKit: pattern-lab/styleguidekit-twig-default
styleguideKitPath: vendor/pattern-lab/styleguidekit-twig-default
plugins:
  faker:
    enabled: true
    locale: en_US
  twigNamespaces:
    enabled: true
    namespaces:
      default_protons:
        paths:
          - ../../../source/default/_patterns/00-protons
          - ../../../source/default/_patterns/00-protons/utilities
      default_atoms:
        paths:
          - ../../../source/default/_patterns/01-atoms
          - ../../../source/default/_patterns/01-atoms/alert
          - ../../../source/default/_patterns/01-atoms/badge
          - ../../../source/default/_patterns/01-atoms/boogie-bear
          - ../../../source/default/_patterns/01-atoms/branding
          - ../../../source/default/_patterns/01-atoms/breadcrumb
          - ../../../source/default/_patterns/01-atoms/button
          - ../../../source/default/_patterns/01-atoms/dropdown
          - ../../../source/default/_patterns/01-atoms/grid
          - ../../../source/default/_patterns/01-atoms/image
          - ../../../source/default/_patterns/01-atoms/list-group
          - ../../../source/default/_patterns/01-atoms/new-cool-thing
          - ../../../source/default/_patterns/01-atoms/new-thang
          - ../../../source/default/_patterns/01-atoms/newer-cool-thing
          - ../../../source/default/_patterns/01-atoms/smelly-diapers
          - ../../../source/default/_patterns/01-atoms/sooper-important-atom
          - ../../../source/default/_patterns/01-atoms/svgicon
      default_molecules:
        paths:
          - ../../../source/default/_patterns/02-molecules
          - ../../../source/default/_patterns/02-molecules/card
          - ../../../source/default/_patterns/02-molecules/carousel
          - ../../../source/default/_patterns/02-molecules/jumbotron
          - ../../../source/default/_patterns/02-molecules/nav
          - ../../../source/default/_patterns/02-molecules/new-molecule
          - ../../../source/default/_patterns/02-molecules/newer-molecule
          - ../../../source/default/_patterns/02-molecules/pagination
          - ../../../source/default/_patterns/02-molecules/vue-widget
      default_organisms:
        paths:
          - ../../../source/default/_patterns/03-organisms
          - ../../../source/default/_patterns/03-organisms/accordion
          - ../../../source/default/_patterns/03-organisms/article
          - ../../../source/default/_patterns/03-organisms/card-grid
          - ../../../source/default/_patterns/03-organisms/footer
          - ../../../source/default/_patterns/03-organisms/navbar
          - ../../../source/default/_patterns/03-organisms/throat-punch
      default_templates:
        paths:
          - ../../../source/default/_patterns/04-templates
          - ../../../source/default/_patterns/04-templates/basic-page
      default_pages:
        paths:
          - ../../../source/default/_patterns/05-pages
